on:
  push:
    branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

jobs:
  release:
    name: Publish binary for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
        include:
          # - os: macos-12
          #   artifact_name: playarr
          #   asset_name: playarr-macos-amd64
          - os: windows-2022
            artifact_name: playarr.exe
            asset_name: meilisearch-windows-amd64.exe
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --release --locked