on:
  release:
    types: [published]

jobs:
  release:
    name: Publish binary for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, ubuntu-latest, windows-2022]
        include:
          - os: macos-12
            artifact_name: playarr
            asset_name: playarr-macos-amd64
          - os: ubuntu-latest
            artifact_name: playarr
            asset_name: playarr-linux-amd64
          - os: windows-2022
            artifact_name: playarr.exe
            asset_name: playarr-windows-amd64.exe
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
        
      # windows specific
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
        if: matrix.os == 'windows-2022' 

      # macos
      - name: Install MPV
        if: matrix.os == 'macos-12'
        run: |
          brew update
          brew install mpv
        
      # ubuntu
      - uses: actions/setup-python@v4
        if: matrix.os == 'ubuntu-latest'
        with:
          python-version: '3.10' 

      - name: Install build deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install -y \
              autoconf \
              automake \
              autopoint \
              autotools-dev \
              build-essential \
              cmake \
              curl \
              debhelper \
              default-jre \
              doxygen \
              flatbuffers-dev \
              gawk \
              gcc \
              gdc \
              gettext \
              git \
              gperf \
              libasound2-dev \
              libass-dev \
              libavahi-client-dev \
              libavahi-common-dev \
              libbluetooth-dev \
              libbluray-dev \
              libbz2-dev \
              libcap-dev \
              libcdio-dev \
              libcec-dev \
              libcrossguid-dev \
              libcurl4-openssl-dev \
              libcwiid-dev \
              libdbus-1-dev \
              libdrm-dev \
              libegl1-mesa-dev \
              libenca-dev \
              libfdk-aac-dev \
              libflac-dev \
              libfmt-dev \
              libfontconfig1-dev \
              libfreetype6-dev \
              libfribidi-dev \
              libfstrcmp-dev \
              libgcrypt20-dev \
              libgif-dev \
              libgl1-mesa-dev \
              libgles2-mesa-dev \
              libglu1-mesa-dev \
              libgnutls28-dev \
              libgpg-error-dev \
              libgtest-dev \
              libiso9660-dev \
              libjpeg-dev \
              liblcms2-dev \
              liblirc-dev \
              libltdl-dev \
              liblua5.2-dev \
              liblzo2-dev \
              libmicrohttpd-dev \
              libmp3lame-dev \
              libmysqlclient-dev \
              libnfs-dev \
              libnuma-dev \
              libogg-dev \
              libopus-dev \
              libp8-platform-dev \
              libpcre3-dev \
              libplist-dev \
              libpng-dev \
              libpulse-dev \
              libsdl2-dev \
              libshairplay-dev \
              libsmbclient-dev \
              libsndio-dev \
              libspdlog-dev \
              libsqlite3-dev \
              libssl-dev \
              libtag1-dev \
              libtiff5-dev \
              libtinyxml-dev \
              libtool \
              libudev-dev \
              libunistring-dev \
              libva-dev \
              libvdpau-dev \
              libvorbis-dev \
              libvpx-dev \
              libx264-dev \
              libx265-dev \
              libxcb1-dev \
              libxcb-shm0-dev \
              libxcb-xfixes0-dev \
              libxmu-dev \
              libxrandr-dev \
              libxslt1-dev \
              libxt-dev \
              lsb-release \
              mercurial \
              meson \
              nasm \
              ninja-build \
              pkg-config \
              python3-dev \
              python3-pil \
              python3-pip \
              python-is-python3 \
              rapidjson-dev \
              swig \
              texinfo \
              unzip \
              uuid-dev \
              wget \
              yasm \
              zip \
              zlib1g-dev \
              libx11-dev \
              docutils-common \
              rst2pdf
          pip install meson
          pip install ninja

      # generic
      - name: Build
        run: cd playarr-desktop && cargo build --release --locked

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: playarr-desktop/target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}