on:
  release:
    types: [published]

jobs:
  release:
    name: Publish binary for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, ubuntu-latest, windows-2022]
        include:
          - os: macos-12
            artifact_name: playarr
            asset_name: playarr-macos-amd64
          - os: ubuntu-latest
            artifact_name: playarr
            asset_name: playarr-linux-amd64
          - os: windows-2022
            artifact_name: playarr.exe
            asset_name: playarr-windows-amd64.exe
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
        
      # windows specific
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
        if: matrix.os == 'windows-2022' 

      # macos
      - name: Install MPV
        if: matrix.os == 'macos-12'
        run: |
          brew update
          brew install mpv
        
      # ubuntu
      - name: Install build deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update -y
          sudo apt install -y mpv libmpv-dev

      # generic
      - name: Build
        run: cd playarr-desktop && cargo build --release --locked

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: playarr-desktop/target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}